// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char DEVICE_LOGIN_NAME[]  = "f77a91f9-aa81-4591-8533-d3fd93abf2e6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onStateChange();
void onSw1Change();
void onSw2Change();
void onSw3Change();
void onSw4Change();

String state;
bool sw1;
bool sw2;
bool sw3;
bool sw4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(state, READWRITE, ON_CHANGE, onStateChange);
  ArduinoCloud.addProperty(sw1, READWRITE, ON_CHANGE, onSw1Change);
  ArduinoCloud.addProperty(sw2, READWRITE, ON_CHANGE, onSw2Change);
  ArduinoCloud.addProperty(sw3, READWRITE, ON_CHANGE, onSw3Change);
  ArduinoCloud.addProperty(sw4, READWRITE, ON_CHANGE, onSw4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
